name: jiffy
description: Jiffy is a date dart package inspired by momentjs for parsing, manipulating and formatting dates
version: 3.0.2
author: Tamilarasan

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  intl: 0.17.0-nullsafety.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter
