name: jiffy
description: Jiffy is a date dart package inspired by momentjs for parsing, manipulating and formatting dates
version: 3.3.1
author: Tamilarasan

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: 0.17.0

dev_dependencies:
  pedantic: ^1.11.0
  lints: ^3.0.0
  test: ^1.24.9
  flutter_test:
    sdk: flutter
